#!/bin/bash

set -ex

if [[ ! -e "cp" ]] || [[ "cp" -ot "build.boot" ]]; then
    boot dump-cp
fi

lumo_dir=~/git/lumo/target
cljsc_opts=$(cat cljsc_opts.edn)

lumo -c $(cat cp) scripts/lumo/build.cljs
