#!/bin/sh

set -xeu

lumo_dir=~/git/lumo/target
cljsc_opts=$(cat cljsc_opts.edn)

node "$lumo_dir/bundle.js" -c "$lumo_dir" -sfK -e "(require '[lumo.closure :as cc] '[clojure.pprint :refer [pprint]]) (pprint (cc/index-node-modules-dir $cljsc_opts))" > npm-deps.edn
